### ISSUE TITLE
Cannot perform the simulation because `MPO` not defined in `MPSDynamics` issue

### ISSUE THREAD

**Issue by ArthurMcl** [shareloqs/MPSDynamics#9]
Sorry I'm not so familiar with julia... and I failed to use your MPS simulations because one dependency errored. Here're the screenshots of the error report and version of my julia, could you please help me with that? I would really appreciate it. 
![image](https://github.com/user-attachments/assets/b8add347-a353-4ded-89b7-e189ee4dfa84)

**Comment by tfmlaX** [comment]
Hi @ArthurMcl, apologies for the late answer!

I'm looking into it - it's most probably related to a breaking change update of ITensors that we haven't dealt with yet. 

It should be corrected quickly :) 

In the mean time you can always locally comment the `MPOtoVector` method (if you don't use it) in `fundamentals.jl` which raises the error

**Comment by tfmlaX** [comment]
As a quick fix, I have set a compatibility constraint on ITensors to v0.6: This resolves the issue :white_check_mark: 

We will update the compatibilities of the package soon to relax this temporary constraint and keep up-to-date :wink:
